/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Cachorro;
import Model.Cavalo;
import Model.Gato;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author henriquegoebel
 */
public class FormAnimal extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormAnimal
     */
    public FormAnimal() {
        initComponents();
        lblTipoPelo.setVisible(false);
        txtTipoPelo.setVisible(false);
        lblVelocidade.setVisible(false);
        txtVelocidade.setVisible(false);
        lblCor.setVisible(false);
        txtCor.setVisible(false);
        listaCachorro = new ArrayList<Cachorro>();
        listaGato = new ArrayList<Gato>();
        listaCavalo = new ArrayList<Cavalo>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAnimal = new javax.swing.ButtonGroup();
        lblAnimal = new javax.swing.JLabel();
        rbCachorro = new javax.swing.JRadioButton();
        rbGato = new javax.swing.JRadioButton();
        rbCavalo = new javax.swing.JRadioButton();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblVacina = new javax.swing.JLabel();
        formattedtxtVacina = new javax.swing.JFormattedTextField();
        lblTipoPelo = new javax.swing.JLabel();
        txtTipoPelo = new javax.swing.JTextField();
        lblVelocidade = new javax.swing.JLabel();
        txtVelocidade = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Formulário de Animal");
        setPreferredSize(new java.awt.Dimension(800, 600));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        lblAnimal.setText("Animal:");

        buttonGroupAnimal.add(rbCachorro);
        rbCachorro.setText("Cachorro");
        rbCachorro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbCachorroStateChanged(evt);
            }
        });

        buttonGroupAnimal.add(rbGato);
        rbGato.setText("Gato");
        rbGato.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbGatoStateChanged(evt);
            }
        });

        buttonGroupAnimal.add(rbCavalo);
        rbCavalo.setText("Cavalo");
        rbCavalo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbCavaloStateChanged(evt);
            }
        });

        lblNome.setText("Nome:");

        lblID.setText("Número de Identificação:");

        lblPeso.setText("Peso (em kgs):");

        lblVacina.setText("Data da última vacina:");

        formattedtxtVacina.setText("dd/mm/aaaa");

        lblTipoPelo.setText("Tipo de Pelo (curto ou longo):");

        lblVelocidade.setText("Velocidade Máxima (em km/h):");

        lblCor.setText("Cor:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAnimal)
                        .addGap(18, 18, 18)
                        .addComponent(rbCachorro)
                        .addGap(18, 18, 18)
                        .addComponent(rbGato)
                        .addGap(18, 18, 18)
                        .addComponent(rbCavalo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPeso)
                        .addGap(26, 26, 26)
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVacina)
                        .addGap(18, 18, 18)
                        .addComponent(formattedtxtVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipoPelo)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipoPelo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblCor)
                                .addGap(18, 18, 18)
                                .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblVelocidade))
                        .addGap(18, 18, 18)
                        .addComponent(txtVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnimal)
                    .addComponent(rbCachorro)
                    .addComponent(rbGato)
                    .addComponent(rbCavalo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVacina)
                    .addComponent(formattedtxtVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoPelo)
                    .addComponent(txtTipoPelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVelocidade)
                    .addComponent(txtVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCor)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnCadastrar)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public List<Cachorro> listaCachorro;
    public List<Gato> listaGato;
    public List<Cavalo> listaCavalo;
    
    
    
    public List<Cachorro> getListaCachorro() {
        return listaCachorro;
    }

    public List<Gato> getListaGato() {
        return listaGato;
    }

    public List<Cavalo> getListaCavalo() {
        return listaCavalo;
    }
    
    
    
    private void rbCachorroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbCachorroStateChanged
        if(rbCachorro.isSelected()){ 
            lblTipoPelo.setVisible(true);
            txtTipoPelo.setVisible(true);
            lblVelocidade.setVisible(false);
            txtVelocidade.setVisible(false);
            lblCor.setVisible(false);
            txtCor.setVisible(false);
        }
    }//GEN-LAST:event_rbCachorroStateChanged

    private void rbGatoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbGatoStateChanged
        if(rbGato.isSelected()){
            lblTipoPelo.setVisible(false);
            txtTipoPelo.setVisible(false);
            lblVelocidade.setVisible(false);
            txtVelocidade.setVisible(false);
            lblCor.setVisible(true);
            txtCor.setVisible(true);
        }
    }//GEN-LAST:event_rbGatoStateChanged

    private void rbCavaloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbCavaloStateChanged
        if(rbCavalo.isSelected()){
            lblTipoPelo.setVisible(false);
            txtTipoPelo.setVisible(false);
            lblVelocidade.setVisible(true);
            txtVelocidade.setVisible(true);
            lblCor.setVisible(false);
            txtCor.setVisible(false);
        }
    }//GEN-LAST:event_rbCavaloStateChanged

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        /*JOptionPane.showMessageDialog(null, "Animal Cadastrado");*/
        if(rbCachorro.isSelected()){
            
            String textID = txtID.getText();
            textID = textID.replace(",", ".");
            int ID ;
            ID = Integer.parseInt(textID);
            
            String textTipoPelo = txtTipoPelo.getText();
            String textNome = txtNome.getText();
            String textVacina = formattedtxtVacina.getText();
            
            String textPeso = txtPeso.getText();
            double PesoC;
            PesoC = Double.parseDouble(textPeso);
            
            
            Cachorro c = new Cachorro(textTipoPelo, textNome, PesoC, ID, textVacina);
            listaCachorro.add(c);
            String cont = "";
            for (Cachorro cachorroC : listaCachorro) {
                cont += cachorroC.listar()+ "\n";
            }
            JOptionPane.showMessageDialog(null, cont);
        }
        
    }//GEN-LAST:event_btnCadastrarMouseClicked
    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup buttonGroupAnimal;
    private javax.swing.JFormattedTextField formattedtxtVacina;
    private javax.swing.JLabel lblAnimal;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTipoPelo;
    private javax.swing.JLabel lblVacina;
    private javax.swing.JLabel lblVelocidade;
    private javax.swing.JRadioButton rbCachorro;
    private javax.swing.JRadioButton rbCavalo;
    private javax.swing.JRadioButton rbGato;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTipoPelo;
    private javax.swing.JTextField txtVelocidade;
    // End of variables declaration//GEN-END:variables
}
